timhutton/twitter-archive-parser

README.md, parser.py
Thanks to @rossgrady: split by month, write into separate files.
Extra changes: made code more pythonic, updated readme.
This fixes #14 and fixes #15
=> Split markdown into separate files by month

parser.py
Minor change, but without an empty line before the horizontal rule, the "Originally on Twitter" line will be interpreted as a heading.
See, for example, https://www.markdownguide.org/basic-syntax/#horizontal-rule-best-practices which recommends using a blank line either side of a horizontal rule.
=> Add empty lines around horizontal rule

parser.py
=> Output all attached images

parser.py
New example of filename: `2022-04-01-Tweet-Archive-2022-04.md`
Jekyll interprets this as `YYYY-MM-DD-your-title-here.md` so this makes a Jekyll post with the title `Tweet-Archive-2022-04`
Non-Jekyll users get slightly odd filenames but I think it's tolerable.
Thanks to @jwildeboer
=> Write tweets into Jekyll-friendly filenames. This fixes #35

parser.py
I've been playing around a bit with formatting of the generated markdown - I'm sharing this, interested in feedback.
- For replies, construct a header that lists the accounts being replied to, and the links to the tweet being replied to. Removes all reply-to "@username "s from the start of the body. 
- Adds a '> ' quote prefix to all lines in the body.
- Replaces "Originally on Twitter: " with the favicon as a scaled image.
- Removes a case where it looks like video media url was being written unnecessarily to the output.
Example 
Before:
After:
=> Several format changes for generated tweets

parser.py
This is a fix for the use of `removeprefix()` as mentioned in https://github.com/timhutton/twitter-archive-parser/issues/49.
This implements the same logic but without the use of `str.removeprefix()`:
```pycon
>>> body = "@simeon test"
>>> replying_to = re.match(r'^(@[0-9A-Za-z_]* )*', body)[0]
>>> replying_to
'@simeon '
>>> body[len(replying_to):]
'test'
```
=> Remove use of str.removeprefix

download_better_images.py
so that we don't overwrite the original with a potentially incomplete new version.
=> Download media to a temporary file

parser.py
I've made a lot of changes to `download_file_if_larger`. I'm sorry for mixing multiple changes into a single PR, but they evolved in parallel. Here's what this changes:
* Only download file if `byte_size_after != byte_size_before` because it seems *very* unlikely that two versions with same file size are actually different
* Download file even if it is smaller *in bytes*, because less bytes may encode more / better pixels, as pointed out in #51
* After downloading, check image size *in pixels* and use downloaded file if `pixels_after >= pixels_before`
* Reordered contents of log line: index / count, filename, result (uppercase), explanation, downloaded bytes
* Less code repetition for log outputs by prefixes and postfixes into `pref` and `post`
* On error, print `{err}` (not sure if this …
=> Improved decision on whether to download and/or overwrite media

parser.py
When trying to parse JSON from Twitter's JS format, but the JSON is an empty list, the parser would crash with an error in the JSON decoding. With this fix, the method just returns an empty dict instead, so checks for empty content can be made by the caller.
(An additional thought on this: it works for me like this with the empty dict, but I think the method should generally be returning a list instead of a dict? Because Twitter's JSON is (almost) always wrapped in a list at the highest level.)
=> Bugfix: avoid crashes when trying to read one-line (empty JSON) file

parser.py
Older Twitter archives (I have one from 2019) seem to use an array of objects like so:
```
{
"retweeted" : false,
"source" : "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>",
"entities" : {
"hashtags" : [ ],
"symbols" : [ ],
"user_mentions" : [ ],
"urls" : [ ]
},
"display_text_range" : [ "0", "47" ],
"favorite_count" : "5",
"id_str" : "11948217481365XXXXX",
"truncated" : false,
"retweet_count" : "0",
"id" : "119482174813653XXXX",
"created_at" : "Thu Nov 14 03:37:58 +0000 2019",
"favorited" : false,
"full_text" : "example text",
"lang" : "en"
}
```
However, the latest archives have a named `tweet` object, as I'm sure you're aware:
```
{
"tweet": {
"retweeted" : false,
"source" : "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>",
"entities" : { …
```
=> Workaround for older Twitter archive tweet.js tweet objects

parser.py
Minimal first-steps functionality in this PR, since there are several of us looking at this area, including: @flauschzelle, @lenaschimmel, @press-rouch, @n1ckfg
Huge thanks for the work already being shared in the discussions.
I'll do my best to synthesise everyone's thoughts but please be tolerant where I get things wrong! 
Suggested roadmap (from discussion in #6):
1. existing `convert_tweet()` function appends whatever id:handle connections it finds to a data structure of Users. <-- this PR
1. new functionality to parse DMs, using Users, output in some simple way
1. new functionality to parse followers/followings, using Users, output in some simple way
1. new functionality to do remote lookup on Users, to improve the output of the above
=> Collect user_id:handle mappings from JSON

parser.py
This partially fixes #70 but not completely since we don't know many of the handles.
The output text files contain `<handle> https://twitter.com/i/user/<user_id>` where handle is `~unknown~handle~` where not known (sorted to the end). The user_id URLs should still work even if someone has changed their handle.
For my archive, user handles are known for 50% of the followings, and 12% of the followers.
When we have a way of retrieving more user_id:handle mappings then this output will improve.
On the suggested roadmap (from discussion in #6):
1. existing `convert_tweet()` function appends whatever id:handle connections it finds to a data structure of Users. <-- PR #76 
1. new functionality to parse DMs, using Users, output in some simple way
1. new functionality to parse …
=> Parse followers and following, output with handles where known.

parser.py
Closes #79 
We are getting the full metadata and discarding most of it, so we could be doing a lot more with this.
There is a slight inefficiency due to creating new sessions for each of the following, follower, and DM lookups, but I wanted to keep the changes to a minimum for now.
Following and followers tested. DMs not tested as I don't have any.
=> Lookup user handles from Twitter.

parser.py
Output of DMs split up into separate markdown files, one file per conversation. Filenames include the name (or ID if the name is unknown) of the other user.
=> output DMs as one markdown file per conversation

README.md, parser.py
We have several issues that can only be solved if we download some additional tweets:
* #72
* #73
* #39
* #20
* #22
So I tried to lay the groundwork for those. I hope this common framework prevents overlapping implementations as well as redundant tweet downloads.
* add method `get_tweets` from some issue conversation between @timhutton and @press-rouch
* adjusted it a bit to the style of the existing `lookup_users`, which includes the added parameters `include_user` and `include_alt_text`
* introduced a three-pass approach to tweet processing *(if you want to, I can explain my reasoning for this specific implementation choice, but this text is already long and I don't know if you actually want to have a reasoning for it)*:
1. collect known tweet IDs, so that we won't download what we …
=> Base feature: Download tweets which are missing or incomplete

parser.py
There was another bug that I only just found while testing, sorry :/
I didn't reset the markdown to empty before starting a new part file, so the content of each file also included the previous one. Should be fixed with this now.
=> Bugfix: reset markdown for each part

parser.py
Replace the short t.co urls in DM text body with their expanded form, wherever the expanded form is also available in the archive data (which it seems to be in most, maybe even all cases).
=> Expand t.co urls in DMs

parser.py
Add a user prompt asking whether to split the html output by month, the same way as the markdown output is being split.  
The markdown and html filenames use the same pattern.
This closes #103
=> Allow to split the html output by month

parser.py
I've noticed that there's a dozen of path variables at the start of main which do not follow a common naming pattern, and the way that their initializations reference each other makes it difficult to understand what is where:
```
input_folder = '.'
output_media_folder_name = 'media/'
tweet_icon_path = f'{output_media_folder_name}tweet.ico'
output_html_filename = 'TweetArchive.html'
data_folder = os.path.join(input_folder, 'data')
account_js_filename = os.path.join(data_folder, 'account.js')
log_path = os.path.join(output_media_folder_name, 'download_log.txt')
output_following_filename = 'following.txt'
output_followers_filename = 'followers.txt'
user_id_URL_template = 'https://twitter.com/i/user/{}'
dm_output_filename_template = 'DMs-Archive-{}.md'
```
They end in five different …
=> Clean up the names and initializations of path variables

parser.py
Underscores are allowed in twitter handles, but they break markdown rendering if they're not escaped. 
I added escaping in the DMs markdown output - not in the filenames, but (hopefully) everywhere in the content.
=> Bugfix: escape markdown (underscores) in user handles for DMs markdown output

parser.py
Mostly adapted from the code that does the same thing in the convert_tweet method.
Still missing the part that saves the online paths for later lookup of better quality version, because I don't know how the best version online path would look for an image from a DM, it might be very different from the ones in a tweet (assuming this because the structure of the archive's JSON is also different for DMs and tweets).
I also wrote hints for this as TODO comments in the code. And I'm neither sure if DMs can even contain videos anyway, nor if I understood the video URL parsing part correctly... please review and test this. For me, it runs without errors - but this still shouldn't be merged in the current unfinished state.
Help with the missing part would be much appreciated :)
=> Replace image URLs in DMs with links to local files

parser.py
Parsing of direct-messages-group.js and writing to one markdown file per group (splitting up very long ones into parts).
~~Image embedding (and copying, etc.) is still missing here, I will add that (probably) tomorrow.~~
Image embedding is now also implemented here (at the same level of completion as for the non-group DMs in #116).
=> Parse group DMs

parser.py
Implementation of [this TODO](https://github.com/flauschzelle/twitter-archive-parser/blob/04e3a75f96f7117dbf7cec7ef1db99de9643a7f4/parser.py#L983) for the other affected types of data (followings, followers, DMs).
The script now only asks 'Download user data from Twitter? [y/n]' once instead of four times. 
Here is an example snippet of the output from this version: (updated)
```
Parsing ./data/account.js...
Parsing ./data/tweets.js...
Wrote 27264 tweets to *.md and *.html, with images and video embedded from ./media
Parsing ./data/following.js...
found 704 user IDs in followings.
Parsing ./data/follower.js...
found 528 user IDs in followers.
Parsing ./data/direct-messages.js...
found 87 user IDs in direct messages.
Parsing ./data/direct-messages-group.js...
found 140 user IDs in group …
```
=> Extract collecting userids and do handle lookup in bulk

parser.py
Escape markdown control characters in DMs (see #123 for details), and format the DMs markdown output with the message text body as quotes instead of code blocks. 
This way, it looks much more similar to the markdown output of tweets, and embedded images are actually shown in markdown rendering (that was not the case when using code blocks).
=> Escape markdown control chars in DMs and format DM text as quotes

parser.py
Quick-and-dirty implementation of estimated time remaining for media downloads, as suggested in #127. The estimate is least accurate at the start, but gets a little better over time.
Example of how the output looks with this (filenames redacted):
```
...
OK to start downloading? [y/n]y
1/2142 ./media/[FILENAME].jpg: SKIPPED. Online version is same byte size, assuming same content. Not downloaded.
0.0 % done, about 8 minutes 46 seconds remaining...
2/2142 ./media/[FILENAME].jpg: SKIPPED. Online version is same byte size, assuming same content. Not downloaded.
0.1 % done, about 11 minutes 14 seconds remaining...
3/2142 ./media/[FILENAME].jpg: SKIPPED. Online version is same byte size, assuming same content. Not downloaded.
0.1 % done, about 11 minutes 59 seconds remaining...
4/2142 …
```
=> show % done and estimated remaining time for media downloads

parser.py
Add method `get_consent` which ensures that yes/no questions are displayed consistently, users know what the default is, and unexpected inputs are handled more robustly.
(in the current `main`, there are only three places where it is used, but I think that the current and future PRs will add more cases in which consent is required.)
Example output with some context:
```
Parsing ./data/following.js...
31 users are unknown.
Download user data from Twitter (approx 65KB)? [y/N]b
Sorry, did not understand. Please answer with y, n, yes, no, or press enter to accept the default (which
is 'no' in this case, as indicated by the uppercase 'N'.)
Download user data from Twitter (approx 65KB)? [y/N]
Your empty response was assumed to mean 'no' (the default for this question).
Wrote 48 accounts to …
```
=> More consistent / robust questions for consent

parser.py
Draft not ready for merging.
What I did:
* Add a group `create_path_for_file_` methods in `PathConfig` and use them. These are now the central point of configuration for how filenames are constructed from several pieces, and it's very close to the point where folder names and paths are configured.
* Add small helper methods `open_and_mkdirs`, `mkdirs_for_file`
* Added  and used method `rel_url`, which returns the relative URL to go from one file path (e.g. a md or html file) to another (e.g. an embedded image)
* Move class `PathConfig` to the top and add some minimal type annotations, so that IDEs can show helpful tooltips (works with VSCode)
* Add method `migrate_old_output` which looks for leftovers of previous runs in the archive root, and (re)moves them, depending on whether they …
=> Put generated output in its own folder(s). Should fix #99.

parser.py
Just remove a `print` line that prints way to many filenames.
=> Remove listing of moved media files, it's much to verbose.

parser.py
If a DM group has no official name contained in the archive data, the filename is constructed from the handles of the most active users in the group. In groups with mostly inactive users (i.e. users who have sent 0 messages to the group in the archived time interval), this did not work correctly before, because inactive users were not counted for the name construction. 
If the handles of the more active users could not be found, then the filename would just have been made from the group's id instead of including handles of inactive users.
For more human-readable filenames, IDs are not useful. So now the inactive users' handles are used as a fallback if there are not enough known handles of active users.
=> Improve filename building for Group DMs

parser.py
An empty handle in UserData caused a crash in the group DMs parsing. There shouldn't be UserData with handle = None anyway. So I built in a few more checks to prevent that.
=> Bugfix: make sure there are no empty handles in UserData
